services:
  mysql_banco:
    image: mysql:8.0
    container_name: mysql_hevy_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_DATABASE: hevy_insights
      MYSQL_USER: eng_dados
      MYSQL_PASSWORD: senha_segura_123
    ports:
      - "3307:3306"
    volumes:
      - mysql_dados:/var/lib/mysql

volumes:
  mysql_dados: